### ISSUE TITLE
readme.md not updated to adapt bad directory fix

### ISSUE THREAD

**Issue by ajaxjiang96** [dilevin/computer-graphics-raster-images#1]
In the setup section of readme:

> **To get started:** Clone this repository and all its [submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) dependencies using:
> 
>     git clone --recursive https://github.com/alecjacobson/computer-graphics-raster-images.git

This command still clones Alec's unfixed original repo

should be `git clone --recursive https://github.com/dilevin/computer-graphics-raster-images.git`

**Comment by dilevin** [comment]
Oh man thanks for catching this, I merged your pull request.
