### ISSUE TITLE
read_rgba_from_png get wrong width, height and rgba size

### ISSUE THREAD

**Issue by xieruiyuan** [dilevin/computer-graphics-raster-images#16]
Hi, I trying to cout the height, width and rgba size after calling read_rgba_from_png function. 
However the width, height are set to some random negative number and vector size is zero.
I didn't change any given code and I'm using vs 2019 on my local windows 10 pc.

**Comment by dilevin** [comment]
We don’t provide support for the code on windows or osx, only the cdf machines. 

If the problem persists on the cdf machines, please submit a code snippet with test data to this issue.

We cannot provide guidance with issues like this from non-detailed text descriptions only.

**Comment by songfeil** [comment]
@xieruiyuan The problem is probably caused by mismatch between relative path references and working directorys. The input of this function is like ""../data/dog.png"",

**Comment by xieruiyuan** [comment]
I double checked the path and I do change it to the local path. 
I also check the closed issue of last year and it seems it's a platform issue. I will move to cdf machines.
