### ISSUE TITLE
Problem with reading png file?

### ISSUE THREAD

**Issue by yunhaom94** [dilevin/computer-graphics-raster-images#22]
Do we need to change anything in read_rgba_from_png()?

I tried to print elements in rgba vector in write_ppm() and the vector always has size 0, when I was trying to print width and height, they are both -858993460. 

I'm running on Windows with Visual Studio 2019.

**Comment by dilevin** [comment]
We don’t offer support for the assignments under windows. If this problem persists on the cdf machines please post a small code snippet illustrating the problem so we can help debug.

**Comment by AlirezaDX** [comment]
I copied the data folder and pasted it into the build folder and it fixed the issue for me.
I think the idea is that compiling on windows would create a folder i.e. "release" with the executable in it but compiling it on Linux would not create such folder, therefore, the path to the .png files would be inaccurate. I'd suggest copying and pasting the data folder into the build folder as changing the path in main.cpp might affect the compatibility of your program with the potential tester.

**Comment by yunhaom94** [comment]
> 
> 
> I copied the data folder and pasted it into the build folder and it fixed the issue for me.
> I think the idea is that compiling on windows would create a folder i.e. "release" with the executable in it but compiling it on Linux would not create such folder, therefore, the path to the .png files would be inaccurate. I'd suggest copying and pasting the data folder into the build folder as changing the path in main.cpp might affect the compatibility of your program with the potential tester.

Thanks! This worked for me.
