### ISSUE TITLE
Helper functions in .cpp files?

### ISSUE THREAD

**Issue by BlackSpade741** [dilevin/computer-graphics-raster-images#25]
New to C++ so not 100% sure about this, but are we allowed to define helper functions, especially given that we are only supposed to submit .cpp files but not .h files? Do all extra functions need to be defined in header files?

**Comment by songfeil** [comment]
You're not submitting header files so do not modify them. I think it is possible to include only .cpp files, and I personally recommend using lambda expressions to avoid linking errors.

**Comment by BlackSpade741** [comment]
@songfeil Thanks!
