### ISSUE TITLE
width & height when reading from png coming out as large negative numbers.

### ISSUE THREAD

**Issue by NPTP** [dilevin/computer-graphics-raster-images#27]
Hi, maybe this is a Windows specific issue. Running Visual Studio 2019.

The starter code in main.cpp calls "read_rgba_from_png" and the resulting width and height become large negative numbers (perhaps some issue with signing/unsigning ints in this compiler?), making them break the rest of the program on run. This is code that we did not write and have not touched. Anyone else had the same issue/have a fix? Thanks!

**Comment by songfeil** [comment]
#22

**Comment by NPTP** [comment]
Thank you! Solved from the suggestions in #22  . Didn't see the closed issues page.
