### ISSUE TITLE
My output images are slightly different with reference images

### ISSUE THREAD

**Issue by chenzi26** [dilevin/computer-graphics-raster-images#3]
<img width="901" alt="screen shot 2019-01-12 at 6 14 46 pm" src="https://user-images.githubusercontent.com/46636554/51079659-ceb02080-1698-11e9-9e18-5188bc11383b.png">

My output image on the right has higher brightness than the reference image. Is this acceptable and will I lose any mark on this difference?

**Comment by dilevin** [comment]
This is fine
-Dave
