### ISSUE TITLE
Bayer mosaic format?

### ISSUE THREAD

**Issue by NPTP** [dilevin/computer-graphics-raster-images#31]
Hi,
The assignment readme page says 

> The most common is the Bayer pattern. In this assignment, we'll assume the top left pixel is green, its right neighbor is blue and neighbor below is red, and its kitty-corner neighbor is also green.

This implies GBRG pattern (going in order: top left, top right, bottom left, bottom right). But the picture of the mosaic in the readme and the doc string in the provided header file `simulate_bayer_mosaic.h` indicate a BGGR pattern.

(edit: it looks like the provided .png was generated with GBRG, adding ammo to THAT side of the argument)

I would assume we go by the header file, but I just want to be sure: since both patterns are being asked for, which one is the one we should implement?

Thanks!

**Comment by charlesvong** [comment]
Implement the GBRG pattern

**Comment by songfeil** [comment]
Last time I asked the professor he said BGGR. But since this is a late notice, I think I'll give credit either way. I'll update to make sure the starter codes are consistent.
