### ISSUE TITLE
Are we required to remove debug info to console?

### ISSUE THREAD

**Issue by desmondlzy** [dilevin/computer-graphics-raster-images#35]
As title.

I put some `cout` in my code... to write something to the terminal to help me debug. Will they have a negative effect on my grade?

The same question for other coming assignment in this course.

Thanks a lot!

**Comment by dilevin** [comment]
You should remove debugging output statements from your code because they can dramatically slow down execution. This makes grading more tedious for the TAs. While leaving them in won't effect your mark, the polite thing to do is to comment them out.

**Comment by desmondlzy** [comment]
Thanks David! I see your point and I already deleted all debugging statements.

Actually I only had a couple of messages to the console throughout the execution of my program, e.g., after each call of `write_ppm`. I guess that will not flood our TA's terminal and slow down his computer. Is that acceptable?
