### ISSUE TITLE
Compositing: Porter Duff Over operator

### ISSUE THREAD

**Issue by NPTP** [dilevin/computer-graphics-raster-images#41]
It's not entirely clear what we should be using for the compositing (A over B) part of the assignment. Should we be using this (taken from wikipedia) ?
![image](https://user-images.githubusercontent.com/16977354/72574870-9db09000-3898-11ea-8399-98126b139a2b.png)

If not, there is also this operation shown in lecture and the textbook:
![image](https://user-images.githubusercontent.com/16977354/72574924-d3557900-3898-11ea-8020-c328d841b9f9.png)
but it looks like this one can only be used if you have the assumption that the background is opaque, and the header file for `demosaic.h` states that A and B are semi-transparent rgba images so that appears to rule this formula out.

There is also this linear combination given in lecture, but the example shown is Dest Atop, not Over, and it's not clear what parameters are required for Over:
![image](https://user-images.githubusercontent.com/16977354/72575034-20394f80-3899-11ea-898e-15f7325e6b53.png)

I have also looked at the provided link (http://ssp.impulsetrain.com/porterduff.html) but it is very unclear how to formulate the "Over" operation from this (the provided table is not exactly instructive).

I am using the formula from wikipedia (which simplifies to the second one shown when background alpha = 1) for the R, G and B values, which seems to work great, just want to be sure this is what is meant in the assignment spec. However there is one probably more important question - I am not sure of how the alpha channel of C should be calculated from A and B and don't see any clear instruction for that using straight alpha (rather than premultiplied). How do we go about that?

Thank you very much!

**Comment by songfeil** [comment]
You can use the one from wikipedia. Actually the first and the third formula is the same.

**Comment by NPTP** [comment]
Thank you. So we use this same formula for the alpha channel as well, treating the alpha values themselves like a colour?

**Comment by songfeil** [comment]
Emm I think in the wiki page they have another equation for alpha value just under the color equation, right? :P

**Comment by NPTP** [comment]
Oh yeah I did see that of course! But I wasn't sure about it because the phrasing implies the equation requires the assumption that all color values are premultiplied by their alpha values. And I'm not sure I understand it all well enough to have extrapolated that piece and knowing it was still valid.
