### ISSUE TITLE
Porterduff over operator

### ISSUE THREAD

**Issue by RaihanFaruque** [dilevin/computer-graphics-raster-images#44]
When I used this  formula in wikipedia page
![wikipedia_formula](https://user-images.githubusercontent.com/59985990/72581641-0ce4af00-38ae-11ea-8efc-0ff476809d16.PNG)

I set the resulting alpha to 255;

This is the result I got:
![porterduff_wikipedia](https://user-images.githubusercontent.com/59985990/72581654-18d07100-38ae-11ea-8fe1-dae537f8ae79.PNG)

When I use this formula: 
![android_formula](https://user-images.githubusercontent.com/59985990/72582320-57ffc180-38b0-11ea-8750-79c4fcfd9840.PNG)
I get this result:
![Porterduff_android](https://user-images.githubusercontent.com/59985990/72582330-6057fc80-38b0-11ea-8c5a-f63615a3ca13.PNG)

Not sure what is causing the problem

**Comment by dilevin** [comment]
The major issue is not the formula you are using. 

Hint 1: what is the alpha for an opaque pixel ?
Hint 2: its not 255.

**Comment by NPTP** [comment]
May not be related to your problem, but with the first formula, I initially got a similar looking image just by forgetting to make sure I was using floats/doubles when normalizing my alpha values, so that they all just turned into zeros (alpha_a and alpha_b).

**Comment by RaihanFaruque** [comment]
Thank you. It works after I divided by 255.0
