### ISSUE TITLE
Problem with hue_shift

### ISSUE THREAD

**Issue by RaihanFaruque** [dilevin/computer-graphics-raster-images#47]
My hue shift produces this result:
![screenshot](https://user-images.githubusercontent.com/59985990/72646019-0fddaf00-3943-11ea-8747-075e6f50d2e4.png)

but my desaturate produces the correct result. What is causing this?

**Comment by songfeil** [comment]
This is quite like the situation where hue is below 0 or beyond 360. Check if there's any hue out of bounds and add/substract corresponding values to make it fall in [0, 359].
