### ISSUE TITLE
Having trouble with Hue Shift and Desaturate

### ISSUE THREAD

**Issue by BlackSpade741** [dilevin/computer-graphics-raster-images#50]
I followed the formulas given in the Wikipedia page, but my images end up looking too green/too red, and I'm not sure what the problem is:

shifted:
![image](https://user-images.githubusercontent.com/24865967/72648767-e5dbbb00-3949-11ea-992c-f65c79b68558.png)

desaturate:
![image](https://user-images.githubusercontent.com/24865967/72648800-f855f480-3949-11ea-968c-58f63b0512c6.png)

**Comment by songfeil** [comment]
If both images are incorrect I suggest you look into your hsv/rgb conversion. The formulas on the wiki pages are correct.
