### ISSUE TITLE
teach.cs machine generating different images than windows

### ISSUE THREAD

**Issue by Blucia** [dilevin/computer-graphics-raster-images#58]
Everything looks good on my windows 10 build but when i run the code on teach.cs machines (via ssh) i get different results for shifted and desaturated. 

![Desktop 2023-09-20 12-03-18 AM-248](https://github.com/dilevin/computer-graphics-raster-images/assets/33040761/2bf5c828-e9d2-4f2f-9021-208d0b7bc734)

Is there some kind of rounding or casting issue specific to linux?

**Comment by wenzhi-guo** [comment]
Rounding issue shouldn't cause such a big difference in output. I would suggest pick a couple pixel values, step through the logic (e.g. print outputs of each step to the console) and try to locate which function is causing the difference.
