### ISSUE TITLE
desaturation factor 

### ISSUE THREAD

**Issue by WyattLiu** [dilevin/computer-graphics-raster-images#6]
The saturation of two example files does not agree (desaturated.png desaturated.ppm.png), which one should we mimic? It is fairly trivial to get close to desaturated.png but when I try to get desaturated.ppm.png with a change in math, I ended up with very desaturated pictures.

*factor or *(1-factor)?

**Comment by rin-23** [comment]
desaturated.png

**Comment by jritch** [comment]
According to Gavin, matching either of the two example images is fine as long as the approach is correct.
