### ISSUE TITLE
Inconsistency in Bayer Pattern Used for `demosaic`

### ISSUE THREAD

**Issue by LanceLi1416** [dilevin/computer-graphics-raster-images#64]
There is an inconsistency in the Bayer pattern used for the `demosaic` function.

- According to [README.md\#Mosaic images](https://github.com/dilevin/computer-graphics-raster-images/tree/master?tab=readme-ov-file#mosaic-images), [README.md\#src/demosaic.cpp](https://github.com/dilevin/computer-graphics-raster-images/tree/master?tab=readme-ov-file#srcdemosaiccpp) and [include/simulate_bayer_mosaic.h\#L17](https://github.com/dilevin/computer-graphics-raster-images/blob/86a195d0f7ffbebbdbcec09efdbfa798f7450e30/include/simulate_bayer_mosaic.h#L17), the pattern used is **GBRG**:
  > In this assignment, we'll assume the top-left pixel is green, its right neighbor is blue, the neighbor below is red, and its [kitty-corner](https://en.wiktionary.org/wiki/kitty-corner#Adverb) neighbor is also green.

  > Given a mosaiced image (interleaved GBRG colors in a single channel), created a 3-channel rgb image.
  
  > ```cpp
  > // Outputs:
  > //   bayer  width*height array containing interleaved color intensities in the
  > //     GBRG Bayer pattern.
  > ```

- However, in [include/demosaic.h\#L5](https://github.com/dilevin/computer-graphics-raster-images/blob/86a195d0f7ffbebbdbcec09efdbfa798f7450e30/include/demosaic.h#L5), the Bayer pattern is indicated as **BGGR**:
  > ```cpp
  > // Given a mosaiced image (interleaved BGGR colors in a single channel), create
  > // a 3-channel RGB image.
  > ```

Could we clarify which Bayer pattern should be used consistently across the assignmnt?

Thank you!

**Comment by dilevin** [comment]
Thanks for catching this please use BGGR for both (no marks deducted if you follow what’s in the headers)

**Comment by Zhecheng-Wang** [comment]
Hi, thank you for noticing this, the inconsistency has been fixed. Please use GBRG for both if possible, thanks!
