### ISSUE TITLE
RGB to HSV: What is the range of RGB values?

### ISSUE THREAD

**Issue by jennicao** [dilevin/computer-graphics-raster-images#66]
For converting between RGB and HSV, is the range of red, green, and blue intensities 0 to 1, or 0 to 255?

The two header files below say 0 to 1, but I just want to double check.

<img src="https://github.com/user-attachments/assets/be63b324-b020-4a27-88db-5694a4b8ef34" width="500">

<img src="https://github.com/user-attachments/assets/5934b349-8ca6-4748-8bb8-6950680b458f" width="500">

**Comment by Zhecheng-Wang** [comment]
0 to 1 for those two. When I mentioned 0-255 in the tutorial it was referring to most function outputs (that will directly write to a ppm file so the range is 0-255).
