### ISSUE TITLE
Demosaic Bayer pattern?

### ISSUE THREAD

**Issue by willgc88** [dilevin/computer-graphics-raster-images#71]
Is the given mosaiced image in BGGR or GBRG pattern? In the header file it says both:
Also, which pattern should we use for simulate_bayer_mosaic?

// Given a mosaiced image (interleaved BGGR colors in a single channel), created
// a 3-channel rgb image.
//
// Inputs:
//   bayer  width*height array containing interleaved color intensities in
//     the GBRG bayer pattern.
//   width  image width (i.e., number of columns)
//   height  image height (i.e., number of rows)
// Outputs:
//   rgb  width*height*3 array containing rgb image color intensities

**Comment by dilevin** [comment]
See here: https://github.com/dilevin/computer-graphics-raster-images/issues/64
