### ISSUE TITLE
Running raster.exe does not produce any ppm files on Windows 10

### ISSUE THREAD

**Issue by shaibalmuhtadee** [dilevin/computer-graphics-raster-images#78]
I built the `raster.exe` using Visual Studio by opening the `raster.sln` file and going to `Build>Build Solution` and it finished without any errors. Whenever I run the exe, it opens a command prompt window for a split second before disappearing and there are no `.ppm` files created in my build folder. They aren't in the Debug folder either. I even implemented `src/rgba_to_rbg.cpp` and then tried running the raster executable again and it did not create any .ppm files.

**Comment by Zhecheng-Wang** [comment]
Did you implement write to ppm? If not, it shouldn't output anything.

**Comment by shaibalmuhtadee** [comment]
Yup, just had to implement the `write_ppm.cpp` file correctly 😅
