### ISSUE TITLE
png width & height are zero

### ISSUE THREAD

**Issue by bethbertozzi** [dilevin/computer-graphics-raster-images#8]
when I run raster this happens, and when I open dog.png from terminal I am given this warning: "eom:22117): Gtk-WARNING **: Allocating size to EomStatusbar 0x560a001b46c0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?"

**Comment by dilevin** [comment]
What machine/os are you trying this on. What program are you using to open the file ? Are you on a local machine or doing this via remote access? If via remote access what command /utility are you using ?

**Comment by bethbertozzi** [comment]
Linux - locally on the ece workstations. I used xdg-open dog.png when I opened the file. I ended up completing the assignment on my personal computer and didn't run into this problem.

**Comment by dilevin** [comment]
ok thanks, we've never seen this bug before. Do you know what distribution of linux the ece workstations run and what version ?
