### ISSUE TITLE
Marking

### ISSUE THREAD

**Issue by Kushagra-Raghuvanshi** [dilevin/computer-graphics-raster-images#80]
Will the scripts be run on teach.cs for marking purposes?
i have tested my outputs on mac but not teach.cs

Can someone provide instruction to test it on teach.cs using ssh

**Comment by Zhecheng-Wang** [comment]
I will grade it on my own Linux machine.
In general if it runs on Mac it will be fine.
For teaching lab ssh, [see here](https://www.teach.cs.toronto.edu/using-labs/remote-command-line-ssh/).
