### ISSUE TITLE
Tips for debugging?

### ISSUE THREAD

**Issue by lulu-yunze** [dilevin/computer-graphics-raster-images#82]
Hi,

I'm new to C++ and am struggling with how to debug the assignment. It seems like raster.exe only generates the .ppm file which is empty for the task I'm debugging. I also tried compiling main.cpp and putting cout statements but have still been stuck trying to find the problem for hours.

I would really appreciate any recommendations on how to debug more efficiently. Thanks in advance!

**Comment by Zhecheng-Wang** [comment]
Hi, can you try the following:
- make sure write to ppm is implemented correctly (you need to implement this first to see some output)
- start with simpler tasks like reflection

If you have done those, please post a detailed log (e.g. which function is buggy, what have you tried).

**Comment by lulu-yunze** [comment]
I figured it out, thanks!
