### ISSUE TITLE
Question about Desaturate

### ISSUE THREAD

**Issue by yangh122** [dilevin/computer-graphics-raster-images#83]
Hi, I am wondering if the images under the image folder are the correct output.

When I compared my output with the desaturated image under the image folder, I noticed slight differences, particularly in the right ear region.

Then I took the pixel at coordinates (293,91) from the original image, and its RGB value was [60, 3, 7]. However, the same pixel in the desaturated image from the image folder has the value [16, 16, 16], which does not match the value I calculated using the formula.

![image](https://github.com/user-attachments/assets/b671d4b0-f25e-45c6-9bd4-87bc8d184aac)
![image](https://github.com/user-attachments/assets/ba275ac3-8ec0-4ddd-8a77-33608c4dea05)

**Comment by Danx1129** [comment]
I also have the same question. 
![Screenshot 2024-09-15 at 2 20 35 AM](https://github.com/user-attachments/assets/a9b397e2-0daf-425c-93a8-86ef66718186)
The image on the left is provided /image/desaturated.png, while the image on the right is created by my code. As you can see, the region above the nose is greener for the provided image. However, I also tried using an online tool to desaturate the provided /image/rgb.png by 25% and received a result closer to my image compared to provided image (the region above the nose is NOT green). 
![desat 25%](https://github.com/user-attachments/assets/6fc7e6ad-3d13-4615-8371-4b603c30da09)

**Comment by Zhecheng-Wang** [comment]
Hi, we noticed that some PNG files seem corrupted or compressed. [We now provide reference PPM files here](https://github.com/dilevin/computer-graphics-raster-images/tree/e7910f6e45a01b446dfce6e3d6181bfee0d21e88/data/validation). Note that you don't have to match the PPM file line by line, only matching the RGB value is fine.

**Comment by yangh122** [comment]
Should we expect to have the exact same values, or is there an acceptable margin of error?

**Comment by Zhecheng-Wang** [comment]
The grading script allows some margin of error for most of the tasks. But some are checked for exact values (namely write_to_ppm, reflection, rotate).

**Comment by yangh122** [comment]
Feel like the reference PPM file has a little bit error. 
For example, in the bayer.ppm data part, the line[0], position[54],[56] and line[1] position[55] value is 212 212 212. For line[0] position[55], since we are using GBRG pattern, it represents a B value. So its demosaickedG value should be (212+212+212)/3 = 212.
But in demosaicked.ppm for line[0] position[166] value is 210.

**Comment by Zhecheng-Wang** [comment]
I haven't checked the pixel value of those pixels, but if those pixels are indeed the neighbouring pixels, I agree it should be 212.
That being said, the tests are really lenient on numerical differences IMO. And I will manually check all solutions that are marked as different by tests.

**Comment by cassandratin13** [comment]
> The grading script allows some margin of error for most of the tasks. But some are checked for exact values (namely write_to_ppm, reflection, rotate).

How large is this margin of error? For the files that don't require exact values, is a difference of up to 6 acceptable?
