### ISSUE TITLE
Issue with demosaic validation image?

### ISSUE THREAD

**Issue by destefy** [dilevin/computer-graphics-raster-images#86]
I think there is an issue with the validation demosaic image provided.

The top left corner of the bayer.ppm validation image is as follows (i've added the brackets)
```
P2
383 385
255
223 {225} 220 ...
[163] 223 [157] ...
```

When we demosaic on the the second pixel ( {255} ) we look to the south west and south east pixels ([163] and [157]) to get the red value for the demosaicked image's second pixel. Based on the validation image, the red value should be 160, since its the average of [163] and [157].

However, when we look at the demosaicked validation image it's as follows (plus the brackets I added):

```
P3
383 385
255
163 223 225 {159 221 225} 157 220 223 ...
```

Here the second pixel ( {159 221 225} ) has a red value of 159!
There are other pixels with discrepancies like this

Please explain if I have misunderstood the demosaicking algorithm.

Thanks!

**Comment by Zhecheng-Wang** [comment]
See #83 . Great observation, I agree. The difference of 1 in pixel value is totally fine, and will be accepted by our grading script.

**Comment by destefy** [comment]
Thank you! I missed that issue.
