### ISSUE TITLE
over.cpp source image looks like static

### ISSUE THREAD

**Issue by chwawa** [dilevin/computer-graphics-raster-images#87]
<img width="493" alt="image" src="https://github.com/user-attachments/assets/27fbcc06-bf4b-4e48-8eb4-8bb5c7179be2">

I'm not sure where I'm going wrong here -- I'm applying the respective straight alpha formulas from [this Wikipedia page](https://en.wikipedia.org/wiki/Alpha_compositing) to all three colour channels (and the alpha channel) for each pixel. 

It seems like the RGB values for the destination image are correct, but something's wrong with the source image... What should I be checking for?

**Comment by Zhecheng-Wang** [comment]
It seems like the pixels you are compositing overflowed, can you double-check to make sure you were operating within [0,1] range for alpha compositing?

**Comment by chwawa** [comment]
Thank you -- that was the problem!
