### ISSUE TITLE
accuracy for hsv functions

### ISSUE THREAD

**Issue by destefy** [dilevin/computer-graphics-raster-images#89]
I've noticed that for my functions that use hsv (demosaicked, desaturated), some pixels colors are off by only 1 (compared to the validation image) due to rounding.

Is this acceptable or will marks be deducted for this?

I've investigated this for hours now and can't find the source of the rounding/truncation.

**Comment by destefy** [comment]
I found this old issue so I'm assuming this is fine

#7

**Comment by Zhecheng-Wang** [comment]
Yes, here to confirm that again. As I mentioned in #83 the tests allow some margin of error, 1 is perfectly fine.

**Comment by destefy** [comment]
Thank you! I missed that issue.
