### ISSUE TITLE
Strange Demosaic Edge 

### ISSUE THREAD

**Issue by grandrx10** [dilevin/computer-graphics-raster-images#91]
Hi, my demosaic image was producing some strange anomalies around the edges of the photo. I am using the GBRB pattern and if there are missing tiles, I ignore them in the averaging process. If the color is directly on the tile, I use the exact color as specified. I was wondering what could be causing the edges to be strangely colored like such?

At the very least, is my conceptualization for how to get the edge colors correct?

![image](https://github.com/user-attachments/assets/c9030b4a-3e7e-49ba-bfa5-bf7d357bae82)

**Comment by Zhecheng-Wang** [comment]
The Bayer pattern should be GRBG.
The interpolation method you described is correct.

**Comment by grandrx10** [comment]
![image](https://github.com/user-attachments/assets/b5ae925f-8462-4121-b539-b6e8099fa78d)
Are you sure that it is GRBG? I thought you stated in a different post that it should be GBRG.

**Comment by Zhecheng-Wang** [comment]
Sorry, it should be GBRG, refer to header file.
You mentioned you used GBRB though.

**Comment by grandrx10** [comment]
Ah, I figured it out. The weird effect was coming with the way I was handling unsigned chars. I apologize for eating up your time, and I thank you for your assistance.
