### ISSUE TITLE
Desaturation Strange Zeroes

### ISSUE THREAD

**Issue by JeremyXie123** [dilevin/computer-graphics-raster-images#92]
For the desaturation step, aside from the +-1 discrepancies between the validation images and the ones I generate, I sometimes get a value of 0 when there shouldn't be.

For context, my rgba -> rgb agrees 1:1 with the validation rgb image. So it must be an issue with my desaturation implementation.

In the image below, I diff compared the image I produced (left) with the validation image (right).

Sometimes the value is zero when the true value is higher (136 in this example), but that's too big to be rounding error?

Considering all the values around it are correct, I'm confused.

If anyone has an idea what I might be doing wrong or encountered a similar issue, I'd appreciate the advice.

![image](https://github.com/user-attachments/assets/4e4cc3b2-6679-40fa-85c2-2bf8e4ae2e07)

**Comment by Zhecheng-Wang** [comment]
"sometimes" usually implies memory related bug.
My suspicion is uninitialized memory.

**Comment by JeremyXie123** [comment]
> "sometimes" usually implies memory related bug. My suspicion is uninitialized memory.

It was always for the same specific few pixels and I found the problem. I was not properly accounting for gray colors where the range was equal to 0 and that resulted in a division by 0.

Thanks, for the help!
