### ISSUE TITLE
Question about Over Operation

### ISSUE THREAD

**Issue by yangh122** [dilevin/computer-graphics-raster-images#94]
Hi, I have a question about over operation.

I found there are two different formulas for the over operation.
1. C_red = A_red *A_alpha + B_red * (1-A_alpha);
2. C_red = (A_red*A_ahpha + B_red*B_alpha*(1-A_alpha))/C_alpha

I am confused about which formula should I use. I also try to run them and one more interesting I found is it seems both of them can work.

**Comment by Zhecheng-Wang** [comment]
2 is correct.

**Comment by yangh122** [comment]
Thanks!
